# Generated by Django 3.2.7 on 2021-10-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name_plural': 'Expense'},
        ),
    ]
