# Generated by Django 3.2.7 on 2021-10-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('SALARY', 'SALARY'), ('BUSINESS', 'BUSINESS'), ('SIDE-HUSTLE', 'SIDE-HUSTLE'), ('OTHERS', 'OTHERS')], max_length=255),
        ),
    ]
