# Generated by Django 3.2.7 on 2021-10-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_alter_income_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Income'},
        ),
    ]
